# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0003_remove_books_lend_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
