# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0006_auto_20171114_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
        migrations.RemoveField(
            model_name='books',
            name='LendBy',
        ),
    ]
