# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0016_auto_20171120_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='foobar', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
