# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0018_auto_20171123_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='subj_code',
            field=models.ManyToManyField(help_text='Select Subject of the book', to='Launcher.Subject'),
        ),
    ]
