# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0019_auto_20171123_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Author_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
