# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0024_auto_20171123_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'On Maintainence'), ('o', 'On Loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Book Availablity', max_length=1),
        ),
    ]
