# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Launcher', '0026_auto_20171123_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Launcher.Books'),
        ),
    ]
